### ISSUE TITLE
week 04 - day 01 - Octocats

### ISSUE THREAD

**Issue by mdewey** [wmurch/assignments#14]
# React-ified Octocats

Your task is to refactor the static Octodex into a static (non-API) version using React.

You'll identify the main `Component`s on the page and create React components for each, breaking down those `Component`s into smaller ones as needed.

## Objectives

- Learn to identify parts of a web site as `Component`s
- Use `app-app` (GAMMA stack) to build a React project
- Understand and use React components

## Stretch Objectives

- Understand and use "props" in React
- Use `Array.prototype.map` to render a collection of components in React

### Explorer Mode

- [ ] [Use this HTML and CSS](https://gist.github.com/mdewey/963d50c11ee90054d1542fd4957e2e9e) as a starting point
- [ ] Figure out the main components of the page. These will be the main components in your `<App>` component.
- [ ] You should have at _least_ two components...
- [ ] Create your React app
- [ ] Copy the CSS from the template into `index.css`
- [ ] Clear out the implementation in the `render` method of `App` and have it render your main components.
- [ ] Create those components and paste the appropriate HTML from the Octodex into the `render` method of those components.
- [ ] Break down those components and use `this.props` to dynamically customize the components that need it.

### Adventure Mode

- [ ] Place the definition of each Octocat in an `array` and use `map` to generate the Octocat components

### Epic Mode

- [ ] Put the `array` of Octocats in an `octocats.json` file and `import` that into your app.
- _OR_
- [ ] Use the `fetch` API to retrieve the list of Octocats from [this api](https://sdg-octodex.herokuapp.com/) instead

## Additional Resources

- [React Documentation](https://reactjs.org/docs/getting-started.html)
- [.map, .reduce & .filter, Oh My!](https://www.datchley.name/working-with-collections/)
- [Array.prototype.map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map)

**Comment by wmurch** [comment]
https://github.com/wmurch/react-octocat

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Ring that bell!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBTQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fabcecd7c921cc4014bfcce0bd127f9e89ef3986/meets-2.gif)
> &ldquo;Ring that bell!&rdquo;
__&mdash; via **[Mark Dewey](https://gifs.suncoast.io/venerations/62)**__
