### ISSUE TITLE
career support - resumes - Build your Resume

### ISSUE THREAD

**Issue by ktrammell95** [wmurch/assignments#23]
Key areas of Information to include:

## Contact information
- [ ] Email
- [ ] Phone Number (Google numbers are great if you want to protect your personal number)
- [ ] Github link
- [ ] Portfolio link

## Summary 
- [ ]  Should be a brief paragraph (three to five sentences) that shows the value you bring by highlighting your skills and a couple of big career wins. But rather than labeling it a “summary,” simply use a headline that encapsulates your credentials.

## Skills 
- [ ]  You’ll want to incorporate the right keywords so that your resume is optimized for application tracking systems

## Professional experience
- [ ]  Focus on your accomplishments rather than your day-to-day responsibilities

## Education
- [ ]  Simply write where you went college and your degree.
- [ ]  It’s ok to move this towards the top if you have limited work experience and want to highlight your experience at SDG

## Bonus:
- [ ]  Volunteering and community service

## Due Date: Wednesday, June 19th
- [ ]  Upload or submit a link to your resume for review.

**Comment by wmurch** [comment]
[Murchison-Willie copy.docx](https://github.com/wmurch/assignments/files/3303705/Murchison-Willie.copy.docx)

**Comment by ktrammell95** [comment]
Nice format, if you don't want to give out your address you could remove that and move your LinkedIn and GitHub info up to that area

Voice:  813-777-3125 
LinkedIn: will-murchison
GitHub: wmurch
wmurch@hotmail.com

and then you don't have to repeat it below. It's just an option to think about.

I would also think about moving your name up into that top area so it ends up on each page should pages get separated.

Double check capitalization you have "react" and "React", there might be more I haven't noticed.

**Comment by ktrammell95** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBWdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3921363294f2f54e76ec6fe9deb21cb56ace25a8/giphy-11.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/76)**__
