### ISSUE TITLE
capstone 03 - Take the next step!

### ISSUE THREAD

**Issue by mdewey** [wmurch/assignments#35]
# Take the next step!

With the wireframes, HTML and CSS created, next up and will be to continue on breathing life into our projects. After the CSS, HTML, and wireframes, we need to start thinking about breathing life into our apps. Take today to start creating your front end, ERD and API definitions.

## Objectives

- Start making your front end dynamic and creating components
- Create an ERD for your database, at least a first draft
- Start thinking about your API

## Explorer Mode

- A React with your HTML and CSS
- a ERD Diagram on paper/whiteboard/image/online builder
- A read me with your API endpoints Defined

**Comment by wmurch** [comment]
![IMG_2186](https://user-images.githubusercontent.com/27396287/60104260-14d0dc00-972f-11e9-8bbf-62861843d1cb.JPG)

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Get up and dance!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBSdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3323b129c4533d8a45339c345692fab77f9771ac/meets-1.gif)
> &ldquo;Get up and dance!&rdquo;
__&mdash; via **[Mark Dewey](https://gifs.suncoast.io/venerations/61)**__
