### ISSUE TITLE
week 01 - day 03  - the daily kitteh

### ISSUE THREAD

**Issue by mdewey** [wmurch/assignments#5]
# Flexbox

Now that we have learned the power of flexbox we will apply it to the sites we are building. We'll also go back to a past assignment and see how flexbox would simplify our HTML and CSS.

## Objectives

- Build on your knowledge of HTML & CSS
- Use flexbox techniques layout pages.
- Implement, from scratch, a given design
- Understand HTML/CSS Layout
- Be able to place elements on a page where you want them.

## Requirements

- You should strive to implement the design as close as possible, though, especially if you've never touch HTML or CSS before, this can be extraordinarily difficult and will take a lot of practice and mileage.

- **Note**: You should complete at least the tasks given for _explorer_ mode as listed below before turning in the assignment, as well as before attempting _adventure_ or _epic_ modes.

### Explorer Mode

- [ ] Recreate the page 'The Daily Kitteh' using flexbox as closely as you possibly can. Use the same fonts, sizes, and colors. 
  - ![daily kitteh](https://suncoast.io/static/239ab85408d42833640e2bc1c19aad71/bf2fc/daily-kitteh.png)

## Adventure Mode

- [ ] Recreate the page `Flebox Article Layout' as closely as possible.
  - ![flexbox article layout](https://suncoast.io/static/44d4ae2c819d83d964a5cd5916e4943f/8d0ff/flexbox-article-layout.png)

## Epic Mode

- [ ] Recreate (Octodex)[https://octodex.github.com/]. Only do enough cats (about 6) to prove that your site is flexing properly
- [ ] Recreate the page `Skeleton Layout example` as closely as possible.
  - ![skeleton layout](https://suncoast.io/static/041402db4c068aa18658c703443e0443/8d0ff/skeleton-layout-example.png)

## Additional Resources

- https://css-tricks.com/snippets/css/a-guide-to-flexbox/
- http://www.evolutionoftheweb.com

## Recommended Practice:

- https://flexboxfroggy.com/
- https://mastery.games/p/flexbox-zombies

**Comment by wmurch** [comment]
https://github.com/wmurch/daily-kitteh

**Comment by mdewey** [comment]
Will, it looks like didn't push your latest code to GitHub. Follow the directions here: https://suncoast.io/handbook/tools/assignment-turn-in and if you need help let me know!

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBWUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fa7a355c1c44cd588feef47afca922431993c337/giphy-9.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/74)**__

**Comment by mdewey** [comment]
My mistake Will, I can see it
